name = "pantas-plus"
author = "pantasmc"
version = "1.21.7-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f1e5c59f676356f7c78bd35c4a42f55abb845904afc0cfe26c661897839779b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
