name = "pantas-plus"
author = "pantasmc"
version = "1.21.7-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c45fb4cb78352f0a6e560d8ea758edcf5dc757f78ea4558a61e2799c4c83fac"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
