name = "pantas-plus"
author = "pantasmc"
version = "1.21.5-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ce2475574ceff9e44d3f30300f3acec9bb55df6e8a6630ee3d17f199037ffce"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
