name = "Momentum"
author = "Ranchod"
version = "1.21.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de09c0f4797e87851ea670e55b4bedabaa73f9d32399246de3ba71c0e9adf53d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
