name = "Pantas"
author = "Ranchod"
version = "1.21.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ebe2e753e5db046ed3d97d593a83fde00b8672bae2fbe25865ee03ac9765b5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
