name = "Pantas"
author = "Ranchod"
version = "1.21.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cac980a8b93f8065f0bba21432b187bcf7cfb426c304098509dbe9bd2c4d9a2"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
