name = "Pantas"
author = "muhdfdeen"
version = "1.21.4-1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d317b97ba504363433805d1408c50c87d03984b1df2baccaf0fa98cb66baa74"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
