name = "pantas-minimal"
author = "pantasmc"
version = "1.21.4-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab8e8cd1c4b44e4e8b4ce42ff1939fd0dcb4b949620e1b400480ec4d74f1bb7"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
