name = "pantas-minimal"
author = "muhdfdeen"
version = "1.21.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "772733607cf124ccec6dc9f7a618e3aeb641330fb374e084c809c73fdeb64ae1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
