name = "pantas"
author = "pantasmc"
version = "1.21.6-3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0629287372dca39d72b4af122bd6b732ce5cf6385a099749df05e8b28e9e5228"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
