name = "pantas"
author = "pantasmc"
version = "1.21.6-2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9c656561531cf4a6d2098b9dfa7f1dcb3ef7ebec1b90cb6182d63b35a1b508b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
