name = "pantas"
author = "pantasmc"
version = "1.21.6-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8d52bd3a9378a5232c14650ab838fc7fbaea3fc599334d2b4978998aeef8691"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
