name = "Pantas"
author = "pantasmc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0361c78379558d04794b07bd40a1b1fd7d4a805ec4661f0790430c2f48ddfe"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
