name = "pantas-minimal"
author = "pantasmc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6783f4758c6c629f9bf20f3e95cdc7c254ae6c151dc0754aceab9f6a2f981647"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
