name = "pantas-minimal"
author = "pantasmc"
version = "1.21.5-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a71a6546316041cc3d91f17eb50391034e7d80d393837c99f8287fcd082c625f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
