name = "pantas"
author = "pantasmc"
version = "1.21.5-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98a9561526c40a71482ca8f34a66a8589e9d681342c2a0cb4049188251c97ccb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
