name = "pantas"
author = "pantasmc"
version = "1.21.5-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398aa93d0e96f27800d960b651eec26e83c9de4b442c003ebbb3128c5e3b4384"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
