name = "pantas"
author = "pantasmc"
version = "1.21.4-3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "197d01e285e5e7a74438551a64ed6ba264ef0a62f7dd51babdf5300bdcafd430"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
