name = "pantas"
author = "pantasmc"
version = "1.21.4-2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29de5847d4cee9708e445dec66ac9b06a423d9ca015f14a13ed11f8f7c606d42"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
