name = "pantas"
author = "pantasmc"
version = "1.21.4-4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4d4dc7d8615f93f39f5ab8ade40b05808a96dabe284be912bd68af53900b564"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
