name = "pantas-plus"
author = "pantasmc"
version = "1.21.4-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33004d54fd5d287fd6010a4dd9f0c478410596dd1d3b0ff31825aa36667aec4b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
